// <auto-generated />
using CodeFirstPractice2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstPractice2.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20210516223432_OrderItem3")]
    partial class OrderItem3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirstPractice2.Context.Item", b =>
                {
                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("ItemName", "Price");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CodeFirstPractice2.Context.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<string>("ItemsItemName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("ItemsPrice")
                        .HasColumnType("real");

                    b.HasKey("OrdersId", "ItemsItemName", "ItemsPrice");

                    b.HasIndex("ItemsItemName", "ItemsPrice");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.HasOne("CodeFirstPractice2.Context.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstPractice2.Context.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsItemName", "ItemsPrice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
